### ISSUE TITLE
[BUG] Qwen2.5-VL TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by testdummyvt** [ModelCloud/GPTQModel#1619]
I tried to quantize Qwen2.5VL 3B model and got `TypeError: 'NoneType' object is not subscriptable` error. 

Data from `allenai/c4`
```python
qwen_dataset = []
for example in calibration_dataset:

    message = [
        {
            "role": "user",
            "content": [
                {"type": "text", "text": example},
            ],
        }
    ]
    qwen_dataset.append(message)
```

```python
model_id = "Qwen/Qwen2.5-VL-3B-Instruct"
quant_config = QuantizeConfig(bits=4, group_size=128)
model = GPTQModel.load(model_id, quant_config)
model.quantize(qwen_dataset, batch_size=1)
```

```bash

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[75], line 2
      1 # increase `batch_size` to match gpu/vram specs to speed up quantization
----> 2 model.quantize(qwen_dataset, batch_size=1)

File ~/code/.venv/lib/python3.11/site-packages/gptqmodel/models/base.py:450, in BaseGPTQModel.quantize(self, calibration_dataset, calibration_dataset_concat_size, batch_size, calibration_enable_gpu_cache, tokenizer, logger_board, backend, buffered_fwd, auto_gc, adapter, adapter_calibration_dataset)
    447 # prepare processor worker (looper)
    448 module_looper = ModuleLooper(self, processors=processors)
--> 450 return module_looper.loop(
    451     calibration_enable_gpu_cache=calibration_enable_gpu_cache,
    452     buffered_fwd=buffered_fwd,
    453     auto_gc=auto_gc,
    454     backend=backend,
    455 )

File ~/code/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py:116, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    113 @functools.wraps(func)
    114 def decorate_context(*args, **kwargs):
    115     with ctx_factory():
--> 116         return func(*args, **kwargs)

File ~/code/.venv/lib/python3.11/site-packages/gptqmodel/looper/module_looper.py:171, in ModuleLooper.loop(self, auto_gc, calibration_enable_gpu_cache, buffered_fwd, **kwargs)
    167             processor.receive_input_cache(InputCache([], [], [], []))
    169         continue
--> 171     input_cache = self.cache_inputs(layers=layers, auto_gc=auto_gc,
    172                                     calibration_data=processor.calibration_dataset,
    173                                     calibration_enable_gpu_cache=calibration_enable_gpu_cache)
    174     processor.receive_input_cache(input_cache)
    176 # release calibration_dataset

File ~/code/.venv/lib/python3.11/site-packages/gptqmodel/looper/module_looper.py:50, in ModuleLooper.cache_inputs(self, layers, auto_gc, calibration_data, calibration_enable_gpu_cache)
     47 position_ids = []
     48 layer_input_kwargs = []
---> 50 cur_layer_device = get_device(layers[0])
     51 data_device = cur_layer_device if calibration_enable_gpu_cache else CPU
     53 # TODO HookLinear add register_forward_pre_hook()

TypeError: 'NoneType' object is not subscriptable

```

**Comment by Qubitium** [comment]
@testdummyvt  Not a bug. You are not providing it with correct calibration data as it is a visual/image model. Please check the following code for sample usage:

https://github.com/ModelCloud/GPTQModel/blob/main/tests/models/test_qwen2_vl.py

**Comment by testdummyvt** [comment]
@Qubitium  Ah! My bad, I fixed that issue already. I copied the wrong output. 


Following is the error I got: `TypeError: 'NoneType' object is not subscriptable`

```bash
Traceback (most recent call last):
  File "/home/azureuser/localfiles/rubes_hagRID/llm_optim/qwenVL/gptq_model.py", line 80, in <module>
    model.quantize(messages, batch_size=1)
  File "/anaconda/envs/hagrid_llm/lib/python3.12/site-packages/gptqmodel/models/base.py", line 490, in quantize
    return module_looper.loop(
           ^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/hagrid_llm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/hagrid_llm/lib/python3.12/site-packages/gptqmodel/looper/module_looper.py", line 186, in loop
    input_cache = self.cache_inputs(layers=layers, auto_gc=auto_gc,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/hagrid_llm/lib/python3.12/site-packages/gptqmodel/looper/module_looper.py", line 57, in cache_inputs
    cur_layer_device = get_device(layers[0])
                                  ~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

When I traced back the code, I found out that the outputs for [`get_module_by_name_prefix`](https://github.com/ModelCloud/GPTQModel/blob/main/gptqmodel/looper/module_looper.py#L166) are `None, ""`

The following are the inputs for that method:

```bash
Qwen2_5_VLForConditionalGeneration(
  (model): Qwen2_5_VLModel(
    (visual): Qwen2_5_VisionTransformerPretrainedModel(
      (patch_embed): Qwen2_5_VisionPatchEmbed(
        (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
      )
      (rotary_pos_emb): Qwen2_5_VisionRotaryEmbedding()
      (blocks): ModuleList(
        (0-31): 32 x Qwen2_5_VLVisionBlock(
          (norm1): Qwen2RMSNorm((1280,), eps=1e-06)
          (norm2): Qwen2RMSNorm((1280,), eps=1e-06)
          (attn): Qwen2_5_VLVisionSdpaAttention(
            (qkv): Linear(in_features=1280, out_features=3840, bias=True)
            (proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (mlp): Qwen2_5_VLMLP(
            (gate_proj): Linear(in_features=1280, out_features=3420, bias=True)
            (up_proj): Linear(in_features=1280, out_features=3420, bias=True)
            (down_proj): Linear(in_features=3420, out_features=1280, bias=True)
            (act_fn): SiLU()
          )
        )
      )
      (merger): Qwen2_5_VLPatchMerger(
        (ln_q): Qwen2RMSNorm((1280,), eps=1e-06)
        (mlp): Sequential(
          (0): Linear(in_features=5120, out_features=5120, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=5120, out_features=2048, bias=True)
        )
      )
    )
    (language_model): Qwen2_5_VLTextModel(
      (embed_tokens): Embedding(151936, 2048)
      (layers): ModuleList(
        (0-35): 36 x Qwen2_5_VLDecoderLayer(
          (self_attn): Qwen2_5_VLSdpaAttention(
            (q_proj): Linear(in_features=2048, out_features=2048, bias=True)
            (k_proj): Linear(in_features=2048, out_features=256, bias=True)
            (v_proj): Linear(in_features=2048, out_features=256, bias=True)
            (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
            (rotary_emb): Qwen2_5_VLRotaryEmbedding()
          )
          (mlp): Qwen2MLP(
            (gate_proj): Linear(in_features=2048, out_features=11008, bias=False)
            (up_proj): Linear(in_features=2048, out_features=11008, bias=False)
            (down_proj): Linear(in_features=11008, out_features=2048, bias=False)
            (act_fn): SiLU()
          )
          (input_layernorm): Qwen2RMSNorm((2048,), eps=1e-06)
          (post_attention_layernorm): Qwen2RMSNorm((2048,), eps=1e-06)
        )
      )
      (norm): Qwen2RMSNorm((2048,), eps=1e-06)
      (rotary_emb): Qwen2_5_VLRotaryEmbedding()
    )
  )
  (lm_head): Linear(in_features=2048, out_features=151936, bias=False)
) 
```
 and 
```
['model.layers']
```

So, I think `get_module_by_name_prefix` is not finding `'model.layers'` as the model has `'model.visual.layers'` and `'model.language_model.layers'`.

**Comment by testdummyvt** [comment]
@Qubitium  Ah! My bad, I fixed that issue already. I copied the wrong output. 

Following is the error I got:

```bash
Traceback (most recent call last):
  File "/home/azureuser/localfiles/rubes_hagRID/llm_optim/qwenVL/gptq_model.py", line 80, in <module>
    model.quantize(messages, batch_size=1)
  File "/anaconda/envs/hagrid_llm/lib/python3.12/site-packages/gptqmodel/models/base.py", line 490, in quantize
    return module_looper.loop(
           ^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/hagrid_llm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/hagrid_llm/lib/python3.12/site-packages/gptqmodel/looper/module_looper.py", line 186, in loop
    input_cache = self.cache_inputs(layers=layers, auto_gc=auto_gc,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/hagrid_llm/lib/python3.12/site-packages/gptqmodel/looper/module_looper.py", line 57, in cache_inputs
    cur_layer_device = get_device(layers[0])
                                  ~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

When I traced back the code, I found out that the outputs for [`get_module_by_name_prefix`](https://github.com/ModelCloud/GPTQModel/blob/main/gptqmodel/looper/module_looper.py#L166) are `None, ""`

The following are the inputs for that method:

```bash
Qwen2_5_VLForConditionalGeneration(
  (model): Qwen2_5_VLModel(
    (visual): Qwen2_5_VisionTransformerPretrainedModel(
      (patch_embed): Qwen2_5_VisionPatchEmbed(
        (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
      )
      (rotary_pos_emb): Qwen2_5_VisionRotaryEmbedding()
      (blocks): ModuleList(
        (0-31): 32 x Qwen2_5_VLVisionBlock(
          (norm1): Qwen2RMSNorm((1280,), eps=1e-06)
          (norm2): Qwen2RMSNorm((1280,), eps=1e-06)
          (attn): Qwen2_5_VLVisionSdpaAttention(
            (qkv): Linear(in_features=1280, out_features=3840, bias=True)
            (proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (mlp): Qwen2_5_VLMLP(
            (gate_proj): Linear(in_features=1280, out_features=3420, bias=True)
            (up_proj): Linear(in_features=1280, out_features=3420, bias=True)
            (down_proj): Linear(in_features=3420, out_features=1280, bias=True)
            (act_fn): SiLU()
          )
        )
      )
      (merger): Qwen2_5_VLPatchMerger(
        (ln_q): Qwen2RMSNorm((1280,), eps=1e-06)
        (mlp): Sequential(
          (0): Linear(in_features=5120, out_features=5120, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=5120, out_features=2048, bias=True)
        )
      )
    )
    (language_model): Qwen2_5_VLTextModel(
      (embed_tokens): Embedding(151936, 2048)
      (layers): ModuleList(
        (0-35): 36 x Qwen2_5_VLDecoderLayer(
          (self_attn): Qwen2_5_VLSdpaAttention(
            (q_proj): Linear(in_features=2048, out_features=2048, bias=True)
            (k_proj): Linear(in_features=2048, out_features=256, bias=True)
            (v_proj): Linear(in_features=2048, out_features=256, bias=True)
            (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
            (rotary_emb): Qwen2_5_VLRotaryEmbedding()
          )
          (mlp): Qwen2MLP(
            (gate_proj): Linear(in_features=2048, out_features=11008, bias=False)
            (up_proj): Linear(in_features=2048, out_features=11008, bias=False)
            (down_proj): Linear(in_features=11008, out_features=2048, bias=False)
            (act_fn): SiLU()
          )
          (input_layernorm): Qwen2RMSNorm((2048,), eps=1e-06)
          (post_attention_layernorm): Qwen2RMSNorm((2048,), eps=1e-06)
        )
      )
      (norm): Qwen2RMSNorm((2048,), eps=1e-06)
      (rotary_emb): Qwen2_5_VLRotaryEmbedding()
    )
  )
  (lm_head): Linear(in_features=2048, out_features=151936, bias=False)
) 
```
 and 
```
['model.layers']
```

So, I think `get_module_by_name_prefix` is not finding `'model.layers'` as the model has `'model.visual.layers'` and `'model.language_model.layers'`.

**Comment by Qubitium** [comment]
@LRL-ModelCloud  check this.

**Comment by lxrlxrrr** [comment]
> [@testdummyvt](https://github.com/testdummyvt) [@DrXuQian](https://github.com/DrXuQian) 我们无法在 上重现此错误`master`。请检查您是否正在使用`master`。

I encountered the same error when quantizing a GPTQModel based on a LoRA fine-tuned and merged version of Qwen2.5-VL-7B-Instruct.

I also checked the repository, and it only contains a main branch — there is no master branch. We're currently working off main, which appears to be the default (origin/HEAD -> origin/main). Could you please confirm whether you meant main instead of master?

**Comment by DrXuQian** [comment]
@Qubitium  I still get this error after using TestQwen2_VL in tests/models/test_qwen2_vl.py. I am using transformers==4.52.3
qwen-vl-utils==0.0.8

**Comment by DrXuQian** [comment]
I downgraded Transformers to 4.51.2 and it works.

**Comment by Qubitium** [comment]
@lxrlxrrr  @DrXuQian  Sorry. the `master` was typo. github uses `main` but our private repos use `master` so I always mix-up the two. 

Yes, we have confirmed that this is a compat regression caused by latest transformers `4.52.3` and `main 4.53.0-dev`. We can confirm `4.51.2` and `4.51.3`  have no such error. We are checking to see what in the world is going on with latest transformers as this model/layer/module transverse bug is quite low-level and should not have been touched by any transformer upgrade.

**Comment by Qubitium** [comment]
> 
> So, I think `get_module_by_name_prefix` is not finding `'model.layers'` as the model has `'model.visual.layers'` and `'model.language_model.layers'`.
> 

@testdummyvt  Yes. The latest transformers changed (standardized) the placement of visual and text modules for multi-modal models. Fix it right now.
